"""empty message

Revision ID: 4e4a3ab37da2
Revises: fdf426aba027
Create Date: 2020-05-22 12:19:27.192119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4a3ab37da2'
down_revision = 'fdf426aba027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'num_upcoming_shows')
    op.drop_column('Artist', 'num_upcoming_shows')
    # ### end Alembic commands ###
