"""empty message

Revision ID: 675513fddf22
Revises: aed410f53d21
Create Date: 2021-07-08 13:57:13.913388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675513fddf22'
down_revision = 'aed410f53d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
