"""empty message

Revision ID: 096cb96e771e
Revises: 4e4a3ab37da2
Create Date: 2020-05-22 17:00:24.048634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096cb96e771e'
down_revision = '4e4a3ab37da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['id'])
    op.create_unique_constraint(None, 'Venue', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
