"""empty message

Revision ID: fdf426aba027
Revises: 6e75f05b72d4
Create Date: 2020-05-19 16:36:26.770240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf426aba027'
down_revision = '6e75f05b72d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_image_link')
    # ### end Alembic commands ###
